CREATE TABLE TRANSACCION (
    ID_TRANSACCION INT PRIMARY KEY IDENTITY (1, 1),
    TIPO VARCHAR (50) NOT NULL,
    TRANSACCION_DATE DATETIME,
	IMPORTE_A_LA_FECHA INT
);

CREATE TABLE OPCION (
    ID_OPCION INT PRIMARY KEY IDENTITY (1, 1),
    DESCRIPCION VARCHAR (50) NOT NULL,
	CODE VARCHAR (10) NOT NULL,
    UPDATED_DATE DATETIME,
	COSTO INT
);

CREATE TABLE TRA_OPC
(
  ID_TRANSACCION INT,
  ID_OPCION INT,
  CONSTRAINT ID_TRA_OPC PRIMARY KEY (ID_TRANSACCION, ID_OPCION),
  CONSTRAINT FK_TRANSACCION FOREIGN KEY (ID_TRANSACCION) REFERENCES TRANSACCION (ID_TRANSACCION),
  CONSTRAINT FK_OPCION FOREIGN KEY (ID_OPCION) REFERENCES OPCION (ID_OPCION)
);

CREATE TABLE AUTOMOVIL (
    ID_AUTOMOVIL INT PRIMARY KEY IDENTITY (1, 1),
    MODELO VARCHAR (50) NOT NULL,
    CONSTRAINT FK_ID_TRANSACCION FOREIGN KEY (ID_AUTOMOVIL) REFERENCES TRANSACCION (ID_TRANSACCION),
);
